#Name of our action -- call it whatever
name: scrape

#When does it get run?
on:
  #workflow_dispatch means "I can click a button and force it to run"
  workflow_dispatch:
  # this means "on a set schedule" check with cron https://en.wikipedia.org/wiki/Cron
  schedule:
    - cron: '0 0 * * 1'
jobs:
  scrape:
    #This is the system that I want my software to run on.
    runs-on: ubuntu-latest
    
    steps:
      #Download all code from your repo
      - name: Check out this repo
        uses: actions/checkout@v2
        
      #Set up python 3.9
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      #Run pip stuff
      - name: Pip install necessary stuff
        run: pip install pandas beautifulsoup4 requests
          
      # MAKE SURE YOUR SCRAPER FILENAME MATCHES THE FILENAME HERE.
      - name: Run the scraping script
        run: python scraper.py
        
      #rest of code that makes it work
      - name: Commit and push if content changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
